### ISSUE TITLE
Kewl package, but how do I use it?

### ISSUE THREAD

**Issue by EricEdwardBryant** [matthieu-haudiquet/rothSGA#1]
Love the package. Can you expand the README so I know how I might use your package to construct a pipline? Maybe there could even be a function `new_batch()`, or something like that for adding pipeline code to a new batch of SGA screens.

K thx bai :wave:!

**Comment by matthieu-haudiquet** [comment]
Great ideas my friend, I'll talk with my collaborator ASAP to fulfill your needs

👋  👋
